config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#show"

  resources :games, only: %i[index show create update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game.rb
require 'life'

class Game < ApplicationRecord
  belongs_to :user

  def to_generation
    @generation ||= Life::Generation.new(generation, width, height, JSON.parse(grid))
  end

  def next_step!
    gen = to_generation.next_step
    self.generation += 1
    self.grid = gen.grid.to_json
    save!
  end

  def reset!
    self.generation = 1
    self.grid = initial_grid
    save!
  end

  class << self
    def from_string(content, user)
      game = Life::Importer.new.import(content)
      grid = game.grid.to_json
      user.games.create(generation: game.number, width: game.width, height: game.height, grid: grid, initial_grid: grid)
    rescue Life::Error
      nil
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :games
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!

  def show
    @game = Game.find(params[:id])
  end

  def update
    @game = Game.find(params[:id])
    if params[:reset]
      @game.reset!
    else
      @game.next_step!
    end
    redirect_to @game
  end

  def index
    @games = current_user.games.order(:created_at).limit(10)
  end

  def create
    # TODO: discard file if too big
    @game = Game.from_string(input_param.read, current_user)
    if @game
      redirect_to @game
    else
      flash[:alert] = I18n.t('games.invalid_file')
    end
  end

  private

  def input_param
    params[:game][:input]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    @games_count = current_user.games.size if current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
  def game_size(game)
    "#{game.width}x#{game.height}"
  end

  def game_cell(cell)
    class_name = cell ? "alive" : "dead"
    content = cell ? '*' : '·'
    content_tag("div", content, class: "board-cell " + class_name )
  end
end

app/views/games/index.html.haml
%h2= t('games.index.title')

%table
  %thead
    %tr
      %th= t('games.width')
      %th= t('games.height')
      %th= t('games.created_at')
  %tbody
    - @games.each do |game|
      %tr
        %td= link_to game.width, game
        %td= link_to game.height, game
        %td= link_to game.created_at, game

app/views/games/show.html.haml
%div{data: { controller: "games"}}
  %p= t('games.size', size: game_size(@game))
  %p= t('games.generation', generation: @game.generation)

  %p
    = button_to t('games.next_step'), @game
    = button_to t('games.reset'), @game, params: { reset: true }

  .board
    - @game.to_generation.grid.each do |row|
      .board-row
        - row.each do |cell|
          = game_cell(cell)

app/views/home/_logged_in.html.haml
- if @games_count.zero?
  %p= t('home.no_owned_games')
- else
  %p= t('home.owned_games', count: @games_count)
  %p= link_to t('home.games_link', count: @games_count), games_url

= form_for Game.new, multipart: true do |f|
  = f.file_field :input, onchange: "this.form.submit()"

app/views/home/_logged_out.html.haml
%h2= t('home.subtitle')

%p.hero= t('home.hero')

%p= link_to t('home.sign_in'), new_user_session_path

app/views/home/show.html.haml
= render partial: current_user ? 'logged_in' : 'logged_out'

app/views/layouts/application.html.haml
!!! html
%html
  %head
    %title Conway's Game of Life
    %meta{name: "viewport", content:"width=device-width,initial-scale=1"}
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"

  %body
    .user-header
      - if current_user
        %span.user-login= current_user.email
        = button_to t('home.sign_out'), destroy_user_session_path, method: :delete
      - else
        = button_to t('home.sign_in'), new_user_session_path, method: :get

    %h1= link_to t("home.title"), root_url

    - flash.each do |type, msg|
      %div{class: type}= msg
    -# .notice= notice
    -# .alert= alert
    = yield
    = javascript_importmap_tags